config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.select { |bookmark| bookmark.list_id == @list.id }
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add your bookmark for <%= @list.name %></h1>
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Confirm", class: 'btn btn-primary'%>
  <%= link_to "Back", list_path(@list), class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url(<%= image_path('banner.jpg')%>);">
  <div class="container">
    <h1> Build your <strong>movies</strong> inventory here !</h1>
    <p> Sit back and relax!</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

<div class="container">
  <h1>List</h1>
      <% images = ["card_1.jpg","card_2.jpg","card_3.jpg"] %>
      <ul>
        <% @lists.each_with_index do |list, index| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path(images[index]) %>);">
        <%= link_to list.name, list_path(list) %>
        </div>
        <% end %>
      </ul>
        <%= link_to "Create new list", new_list_path, class: 'btn btn-primary' %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add your list</h1>
  <%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Confirm", class: 'btn btn-primary'%>
  <%= link_to "Back", lists_path, class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1>Show Page</h1>
  <%= @list.name %>
  <br>
  <br>
  <p>--------------------------------------------------------------------------------------------</p>
  <h2>Bookmarks</h2>
    <table>
    <tr>
      <th>Movie</th>
      <th>Comment</th>
      <th>Delete?</th>
    </tr>
      <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.movie.title %></td>
        <td><%= bookmark.comment %></td>
        <td><%= link_to "  X", bookmark_path(params[:id]) , method: :delete%></td>
      </tr>
    </table>
  <% end %>
  <br>
  <br>
  <%= link_to "Back", lists_path, class: 'btn btn-secondary' %>
  <%= link_to "Create a bookmark", new_list_bookmark_path(@list), class: 'btn btn-primary' %>
</div>